### ISSUE TITLE
guardiand.bash not matching guardiand:dev.v2 image interface

### ISSUE THREAD

**Issue by maxholloway** [wormhole-foundation/xdapp-book#10]
In the `wormhole-local-validator/` package, I unsuccessfully ran `npm run evm`, and `bash run wormhole.bash` was the culprit. I then ran `bash guardiand.bash` as a one-off, and I saw the following.

```
macbookpro:wormhole-local-validator max$ bash guardiand.bash

        +++++++++++++++++++++++++++++++++++++++++++++++++++
        |   NODE IS RUNNING IN INSECURE DEVELOPMENT MODE  |
        |                                                 |
        |      Do not use --unsafeDevMode in prod.        |
        +++++++++++++++++++++++++++++++++++++++++++++++++++

2022-09-01T14:15:11.809Z        INFO    guardian-0      status server listening on [::]:6060
2022-09-01T14:15:11.829Z        FATAL   guardian-0      invalid PythNet contract address        {"error": "decode: zero length string"}
```

Checking the `guadiand.bash` file, we see that there's no mention of pythnet, which is problematic, since that arg is required to run a guardiand node ([ref](https://github.com/wormhole-foundation/wormhole/blob/dev.v2/node/cmd/guardiand/node.go#L252-L254)).

My guess is that there was an CLI interface breaking change on the image `ghcr.io/wormhole-foundation/guardiand:dev.v2` between the time when this guide was written and now. In that case, could you update this line to refer to a specific guardiand docker image hash where the command worked, OR update the `guardiand.bash` file to stay up to date with wormhole v2 dev?

**Comment by spacemandev-git** [comment]
updated in the most recent push
